language: node_js
node_js:
  - "11"
script:
  - npm install gitbook-cli
  - npm install -g @cloudflare/wrangler
  - mv wrangler.toml.example wrangler.toml
  - gitbook install
  - gitbook build
  - wrangler publish

