language: node_js
node_js:
  - "12"
script:
  - npm install gitbook-cli
  - gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _book
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  on:
    branch: master
